// Library.java
package lms;

import java.util.List;

public class Library {
    private DatabaseManager dbManager;

    public Library(DatabaseManager dbManager) {
        this.dbManager = dbManager;
    }

    public void addBook(String title, String author, int copies) {
        Book newBook = new Book(0, title, author, copies); // ID will be auto-generated by DB
        dbManager.addBook(newBook);
    }

    public Book findBookById(int bookId) {
        return dbManager.getBookById(bookId);
    }

    public void rentBook(int bookId) {
        Book book = findBookById(bookId);
        if (book != null && book.getCopiesAvailable() > 0) {
            dbManager.rentBook(bookId);
            book.setCopiesAvailable(book.getCopiesAvailable() - 1); // Update local book object
        } else {
            System.out.println("Book with ID " + bookId + " is not available for renting.");
        }
    }

    public void returnBook(int bookId) {
        Book book = findBookById(bookId);
        if (book != null) {
            dbManager.returnBook(bookId);
            book.setCopiesAvailable(book.getCopiesAvailable() + 1); // Update local book object
        } else {
            System.out.println("Book with ID " + bookId + " not found.");
        }
    }

    public List<Book> getAvailableBooks() {
        return dbManager.getAvailableBooks();
    }
}